# Generated by Django 3.2.7 on 2021-09-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='checkbox_1',
            field=models.CharField(default='unchecked', max_length=10),
        ),
    ]
