# Generated by Django 3.2.7 on 2021-09-30 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('english', '0005_card_checkbox_3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='checkbox_1',
        ),
        migrations.RemoveField(
            model_name='card',
            name='checkbox_2',
        ),
        migrations.RemoveField(
            model_name='card',
            name='checkbox_3',
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.card')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
