# Generated by Django 3.2.8 on 2021-10-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0006_auto_20210930_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='memo',
            field=models.TextField(blank=True),
        ),
    ]
